version: '3'
services:
  superstore-app:
    image: alexv31/superstore:app
    networks:
      - superstore-network
    ports:
      - "3003:80"
      - "3004:443"

  superstore-api:
    image: alexv31/superstore:api
    depends_on:
      - superstore-db
    environment:
      - NODE_ENV=
      - PORT=
      - JWT_SECRET=
      - MAIL_USER=
      - MAIL_PASSWORD=
      - ALLOWED_ORIGIN=
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - POSTGRES_USERNAME=
      - POSTGRES_PASSWORD=
      - POSTGRES_DATABASE=
    networks:
      - superstore-network
    ports:
      - "4003:80"
      - "4004:443"

  superstore-db:
    image: postgres
    restart: always
    networks:
      - superstore-network
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5003:5432"
      - "5004:443"

volumes:
  postgres_data:

networks:
  superstore-network:
    driver: bridge
