version: '3'
services:
  app:
    image: superstore:app
    networks:
      - my-network
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    image: superstore:api
    networks:
      - my-network
    ports:
      - "3000:3000"
networks:
  my-network:
    driver: bridge
