version: '3'
services:
  app:
    image: alexv31/superstore:front
    networks:
      - my-network
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    image: alexv31/superstore:api
    networks:
      - my-network
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
networks:
  my-network:
    driver: bridge
