version: '3'
services:
  superstore-app:
    image: alexv31/superstore:app
    networks:
      - superstore-network
    ports:
      - "3004:80"
      - "3005:443"

  superstore-api:
    image: alexv31/superstore:api
    depends_on:
      - superstore-db
    environment:
      - NODE_ENV=
      - PORT=
      - JWT_SECRET=
      - MAIL_USER=
      - MAIL_PASSWORD=
      - ALLOWED_ORIGIN=
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - POSTGRES_USERNAME=
      - POSTGRES_PASSWORD=
      - POSTGRES_DATABASE=
      - STRIPE_PRIVATE_KEY=
    networks:
      - superstore-network
    ports:
      - "4004:80"
      - "4005:443"

  superstore-db:
    image: postgres
    restart: always
    networks:
      - superstore-network
    environment:
      - POSTGRES_DB=superstore_local
      - POSTGRES_USER=superstore-dev
      - POSTGRES_PASSWORD=superstore-dev
    ports:
      - "5004:5432"
      - "5005:443"

volumes:
  postgres_data:

networks:
  superstore-network:
    driver: bridge
