version: '3'
services:
  app:
    image: alexv31/superstore:front
    networks:
      - my-network
    ports:
      - "80:80"
    depends_on:
      - api
  
  api:
    image: alexv31/superstore:api
    networks:
      - my-network
    ports:
      - "3000:3000"
  
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge