version: '3'
services:
  superstore-app:
    image: superstore:front
    networks:
      - my-network
    ports:
      - "80:80"

  superstore-api:
    image: superstore:api
    depends_on:
      - superstore-db
    env_file:
      - ./.env
    networks:
      - my-network
    ports:
      - "3000:3000"

  superstore-db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    networks:
      - my-network
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge
