# This is a basic workflow to help you get started with Actions
# This workflow will build a docker image and push it to Docker Hub
# Setup environment variables in your repository settings (name of the environment : production)
# Use portainer API to get the stack id and endpoint id GET (<portainer-url>/api/stacks)
# Use portainer API to get the access token POST (<portainer-url>/api/auth) body {"username":"<username>","password":"<password>"}

name: Docker Build and Deploy

on:
  push:
    branches: [ "170-fix-redeploy-container" ]
  pull_request:
    branches: [ "170-fix-redeploy-container" ]

env:
  APP_NAME: superstore
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  PORTAINER_USERNAME: ${{ secrets.PORTAINER_USERNAME }}
  PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}
  PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
  PORTAINER_ACCESS_TOKEN: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
  PORTAINER_STACK_ID: ${{ secrets.PORTAINER_STACK_ID }}
  PORTAINER_ENDPOINT_ID: ${{ secrets.PORTAINER_ENDPOINT_ID }}

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Portainer Deploy'
        uses: cssnr/portainer-stack-deploy-action@v1
        with:
          token: ${{ env.PORTAINER_ACCESS_TOKEN }}
          url: ${{ env.PORTAINER_URL }}
          name: ${{ env.APP_NAME }}
          file: docker-compose.yml